#!/bin/bash

SCRIPT_DIR=`dirname $0`
DISTRIBUTION_DIR=`dirname $SCRIPT_DIR`

export PATH=/usr/local/bin:$PATH

kubectl stop rc -lname=octo-master
kubectl delete rc -lname=octo-master
kubectl delete pods -lname=octo-master
kubectl create -f $SCRIPT_DIR/octo-master-controller.yaml
